"""Add linked_family_id for citizen

Revision ID: 4d31c0f4174e
Revises: 146912db5072
Create Date: 2026-09-20 17:42:27.089512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d31c0f4174e'
down_revision: Union[str, Sequence[str], None] = '146912db5072'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('linked_family_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'linked_family_id')
    # ### end Alembic commands ###
