"""initial sqlite

Revision ID: e8f4713adf85
Revises: 
Create Date: 2026-09-20 15:23:41.602260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8f4713adf85'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('families',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('head_name', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('taluka', sa.String(), nullable=True),
    sa.Column('village', sa.String(), nullable=True),
    sa.Column('pincode', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('ration_card_type', sa.String(), nullable=True),
    sa.Column('annual_income', sa.Integer(), nullable=True),
    sa.Column('household_status', sa.String(), nullable=True),
    sa.Column('ration_card_status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_families_id'), 'families', ['id'], unique=False)
    op.create_table('schemes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schemes_id'), 'schemes', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('data_conflicts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('family_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('factors', sa.JSON(), nullable=True),
    sa.Column('records', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_conflicts_id'), 'data_conflicts', ['id'], unique=False)
    op.create_table('family_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('family_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('affected_member_id', sa.String(), nullable=True),
    sa.Column('effective_date', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('supporting_reference', sa.String(), nullable=True),
    sa.Column('reported_by', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_events_id'), 'family_events', ['id'], unique=False)
    op.create_table('members',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('family_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('relation', sa.String(), nullable=True),
    sa.Column('aadhaar_ref', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_members_id'), 'members', ['id'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('family_id', sa.String(), nullable=True),
    sa.Column('beneficiary_member_id', sa.String(), nullable=True),
    sa.Column('scheme_id', sa.String(), nullable=True),
    sa.Column('submitted_at', sa.String(), nullable=True),
    sa.Column('current_stage', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('pending_days', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['beneficiary_member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    op.create_table('benefits',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('family_id', sa.String(), nullable=True),
    sa.Column('beneficiary_member_id', sa.String(), nullable=True),
    sa.Column('scheme_id', sa.String(), nullable=True),
    sa.Column('application_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('sanctioned_amount', sa.Integer(), nullable=True),
    sa.Column('paid_amount', sa.Integer(), nullable=True),
    sa.Column('last_transaction', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['beneficiary_member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_benefits_id'), 'benefits', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_benefits_id'), table_name='benefits')
    op.drop_table('benefits')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_members_id'), table_name='members')
    op.drop_table('members')
    op.drop_index(op.f('ix_family_events_id'), table_name='family_events')
    op.drop_table('family_events')
    op.drop_index(op.f('ix_data_conflicts_id'), table_name='data_conflicts')
    op.drop_table('data_conflicts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_schemes_id'), table_name='schemes')
    op.drop_table('schemes')
    op.drop_index(op.f('ix_families_id'), table_name='families')
    op.drop_table('families')
    # ### end Alembic commands ###
